#!/bin/sh
. /usr/sup/use/use.sh
use comp40
for i in midmark.um sandmark.umz
do
        /usr/bin/time -f "um $i: %U seconds (user time)" ./um $i > /dev/null
done
valgrind --tool=callgrind --simulate-cache=yes ./um midmark.um > /dev/null